# Generated by Django 6.0 on 2026-01-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=50),
        ),
    ]
